name: HiTV Auto Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # مهم جداً لتجنب مشاكل الـ push

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install
          npx playwright install chromium --with-deps

      - name: Run Scraper
        run: node scraper.js

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          
          # دمج أي تغييرات خارجية أولاً
          git pull --rebase origin main
          
          git add .
          if git diff --quiet && git diff --staged --quiet; then
            echo "لا توجد تغييرات جديدة."
          else
            git commit -m "تحديث الحلقات والترجمات [skip ci]"
            git push origin main
          fi
